### ISSUE TITLE
Simplify datastructure

### ISSUE THREAD

**Issue by f2r** [strangebuzz/phpquiz#28]
Some data fields appear to be little or not used. Moreover, the relevance of some fields does not always seem to be justified.
The data structure should therefore be simplified and replaced by more open data.

Question entity : 

* [x] id: **OK** for testing 
* [x] reminder: is it used ?? => to delete **DONE**
* [x] label: **OK**, but just a short text on a single line (for listing)
* [x] description: to add. Contains question details with embedded links, images, code snippets, etc. => markdown
* [x] codeImage: to delete and directly embedded into question description body
* [ ] codeImageFile: to delete, like codeImage
* [ ] answerExplanations: OK, but like question description => markdown with links, images, code snippets, etc. as markdown
* [ ] liveSnippetUrl: to delete (embedded into answerExplanations)
* [ ] twitterPollUrl: to rename as sourceUrl (could be nullable)
* [ ] differencesOutputNotes: to delete (embedded into answerExplanations)
* [x] answers: **OK**
* [ ] links: to delete (embedded into description and/or answerExplanations)
* [x] suggestedBy: **OK**
* [ ] previousQuestion/nextQuestion: to delete => previous and next are parts of a quiz, not a question
* [x] difficulty: **OK**, but could be a simple integer level to reduce join complexity

Answer entity:

* [ ] id: to delete => entity relationship is question_id (from question)
* [ ] code: replace by "order: int" to set answers order for a question and manage the user response
* [x] label: **OK**
* [ ] correct: replace by "score: float" because sometime, we can add partial score for multiple choices => 0 = wrong
* [ ] pollResult: to discuss! (see after)

For "pollResult", it could be interesting to keep users score performance in an external table to calculate automatically the question difficulty and generate automatically some random quiz, based on this performance.

**Comment by f2r** [comment]
markdown cannot highlight easily code syntax. Should create custom twig extension to properly highlight PHP syntax using external javascript library

**Comment by COil** [comment]
Dommage de ne pas avoir finis. Je te laisse réouvrir si besoin.
